#!/bin/sh
set -e

[ ! -f /etc/rndc.key ] && echo "Generating rndc.key" && rndc-confgen -a -r /dev/urandom -u named
mv /var/bind/named.ca /etc/bind/db.root
rm -rf /var/bind/*
exec /usr/sbin/named -g -u named
