#!/bin/sh
set -e

echo "Generating rndc.key"
rndc-confgen -a -r /dev/urandom -u named

[ -f /var/bind/named.ca ] \
  && mv /var/bind/named.ca /etc/bind/db.root \
  && rm -rf /var/bind/*

exec /usr/sbin/named -g -u named
